name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      GCC_V: 11


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt install -y gfortran-${GCC_V}
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}
    - name: Install Dependencies MacOS
      if: contains(matrix.os, 'macos')
      run: |
        brew install gcc@${GCC_V}
        sudo ln -s $(which gfortran-${GCC_V}) $(dirname $(which gfortran-${GCC_V}))/gfortran
    - name: Install Dependencies Windows
      if: contains(matrix.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          gcc
          gcc-fortran
    - name: Build and Test Linux and MacOS
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      run: |
        fpm test
    - name: Build and Test Windows
      if: contains(matrix.os, 'windows')
      shell: msys2 {0}
      run: |
        fpm test