name = "json_to_quaff"
version = "0.0.1"
license = "MIT"
author = "Giovanni Facco"
maintainer = "gfacco@gmail.com"
copyright = "2022 Giovanni Facco"

[dependencies]
quaff = { git = "https://gitlab.com/everythingfunctional/quaff"}
rojff = { git = "https://gitlab.com/everythingfunctional/rojff.git" }
erloff = { git = "https://gitlab.com/everythingfunctional/erloff.git"}


[dev-dependencies]
veggies = { git = "https://gitlab.com/everythingfunctional/veggies.git"}
quaff_asserts = { path = "./build/dependencies/quaff/quaff_asserts" }
