name = "json_to_fortran"
version = "0.0.1"
license = "MIT"
author = "Giovanni Facco"
maintainer = "gfacco@gmail.com"
copyright = "2022 Giovanni Facco"

[dependencies]
assert = { git = "https://github.com/sourceryinstitute/assert.git", tag = "1.0.0" }
quaff = { git = "https://gitlab.com/everythingfunctional/quaff"}
rojff = { git = "https://gitlab.com/everythingfunctional/rojff.git" }
erloff = { git = "https://gitlab.com/everythingfunctional/erloff.git"}


[dev-dependencies]
veggies = { git = "https://gitlab.com/everythingfunctional/veggies.git"}